# Generated by Django 4.2.23 on 2026-08-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_brand_category_product_detail_product_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name_brand',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='sale_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
