# Generated by Django 4.2.23 on 2026-09-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_order_history_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_history',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
